fix: 🐛 test permission 6

diff --git a/.github/workflows/start_process.yaml b/.github/workflows/start_process.yaml
--- a/.github/workflows/start_process.yaml
+++ b/.github/workflows/start_process.yaml
@@ -5,16 +5,28 @@ jobs:
     check_your_permission:
         runs-on: ubuntu-latest
         steps:
-            - name: passed
-              if: contains('["yambottle","ttngu207"]', github.actor)
-              run: echo "INFO::Passed"
-            - name: you don't have permission
-              if: contains('["yambottle","ttngu207"]', github.actor)==false
+            - name: Checkout workflow repo
+              uses: actions/checkout@v3
+            - name: check your permission
               run: |
-                  echo "ERROR::Please your repo owner or admin to add your github username to the action secrets"
-                  exit 1
+                  ls -al
+                  export ARE_YOU_ALLOWED=$(grep -Fxq "$GITHUB_ACTOR" ./.github/workflows/start_process_allow_list)
+                  if [ $ARE_YOU_ALLOWED ]
+                  then
+                      echo "INFO::Passed"
+                  else
+                      echo "ERROR::Please make a pull request to add your github username in the .github/workflows/start_process_allow_list"
+                      exit 1
+                  fi
+            # - name: passed
+            #   if: contains('["yambottle","ttngu207"]', github.actor)
+            #   run: echo "INFO::Passed"
+            # - name: you don't have permission
+            #   if: contains('["yambottle","ttngu207"]', github.actor)==false
+            #   run: |
+            #       echo "ERROR::Please your repo owner or admin to add your github username to the action secrets"
+            #       exit 1
     call_context_check:
-        if: contains('["yambottle","ttngu207"]', github.actor)
         needs: check_your_permission
         uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
     start_process:
